// GENERATED by scripts/make_resume.py — do not edit by hand.
// Content hash of public/NARAM_RESUME.pdf, appended to the download URL
// so a regenerated resume can never be served from a stale browser cache.
export const RESUME_VERSION = "bce643b5";
